ProductCatalog.Web/Controllers/ManageAccountsController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProductCatalog.Web.DTOs;
using ProductCatalog.Web.Services;
using ProductCatalog.Web.ViewModels;

namespace ProductCatalog.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ManageAccountsController : Controller
    {
        private readonly IUserApiService _userApiService;
        private readonly IMapper _mapper;

        public ManageAccountsController(
            IUserApiService userApiService,
            IMapper mapper)
        {
            _userApiService = userApiService;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            var users = await _userApiService.GetUsersAsync();
            var usersViewModels = _mapper.Map<List<UserViewModel>>(users);
            
            return View(usersViewModels);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(UpdateUserViewModel userViewModel)
        {
            var userDto = _mapper.Map<CreateUserDto>(userViewModel);
            var response = await _userApiService.CreateUserAsync(userDto);

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction(nameof(Index));
            }

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> LockUser(string id, bool isLocked)
        {
            var response = await _userApiService.LockUserAsync(id, isLocked);

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(string id)
        {
            var userToDelete = await _userApiService.GetUserByIdAsync(id);
            if (userToDelete == null)
            {
                return RedirectToAction("Error", "Home");
            }

            var user = _mapper.Map<UserViewModel>(userToDelete);

            return View(user);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var response = await _userApiService.DeleteUserAsync(id);

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> ChangeUserPassword(string id)
        {
            var user = await _userApiService.GetUserByIdAsync(id);

            if (user == null)
            {
                return RedirectToAction(nameof(Index));
            }

            var userViewModel = _mapper.Map<UpdateUserViewModel>(user);

            return View(userViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> ChangeUserPassword(string id, string password)
        {
            var response = await _userApiService.ChangeUserPasswordAsync(id, password);

            return RedirectToAction(nameof(Index));
        }
    }
}

ProductCatalog.Web/Views/ManageAccounts/ChangeUserPassword.cshtml
@model UpdateUserViewModel
@{
    ViewData["Title"] = "Change user password page";
}
<h4>Change user password</h4>
<form asp-action="ChangeUserPassword" method="post" class="col-md-4">
    <input type="hidden" asp-for="Id" />
    <input type="hidden" asp-for="Email" />
    <div class="mb-3">
        <label class="form-label">Email</label>
        <label>@Model.Email</label>
    </div>
    <div class="mb-3">
        <label class="form-label">Password</label>
        <input asp-for="Password" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
</form>

ProductCatalog.Web/Views/ManageAccounts/Create.cshtml
@model UpdateUserViewModel
@{
    ViewData["Title"] = "Create user page";
}
<h4>Create user</h4>
<form asp-action="Create" method="post" class="col-md-4">
    <div class="mb-3">
        <label class="form-label">Email</label>
        <input asp-for="Email" class="form-control" />
    </div>
    <div class="mb-3">
        <label class="form-label">Password</label>
        <input asp-for="Password" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
</form>

ProductCatalog.Web/Views/ManageAccounts/Delete.cshtml
@model UserViewModel
@{
    ViewData["Title"] = "Delete user page";
}
<h4>Delete user</h4>
<input type="hidden" asp-for="Id" />
<div class="mb-3">@Html.DisplayFor(model => model.Email)</div>
<div class="mb-3">@Html.DisplayFor(model => model.Roles)</div>

<form asp-action="Delete" method="post" class="col-md-4">
    <button type="submit" class="btn btn-primary">Delete</button>
</form>

ProductCatalog.Web/Views/ManageAccounts/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

ProductCatalog.Web/Views/ManageAccounts/Index.cshtml
@model IEnumerable<UserViewModel>
@{
    ViewData["Title"] = "Manage accounts Page";
}
<h4>Manage accounts</h4>
<p>
    @Html.ActionLink("Create", "Create", "ManageAccounts", null, new { @class = "btn btn-primary" })
</p>
<table class="table">
    <thead>
        <tr>
            <th>Email</th>
            <th>Roles</th>
            <th>Is Locked</th>
            <th></th>
        </tr>
    </thead>
    @foreach (var user in Model)
    {
        <tr>
            <td>@Html.DisplayFor(m => user.Email)</td>
            <td>@Html.DisplayFor(m => user.Roles)</td>
            <td>@Html.DisplayFor(m => user.IsLocked)</td>
            <td>
                @Html.ActionLink("Lock", "LockUser", new { id = user.Id, isLocked = !user.IsLocked }, new { @class = "btn btn-outline-success" })
                @Html.ActionLink("Change password", "ChangeUserPassword", new { id = user.Id }, new { @class = "btn btn-outline-warning" })
                @Html.ActionLink("Delete", "Delete", new { id = user.Id }, new { @class = "btn btn-outline-danger" })
            </td>
        </tr>
    }
</table>